#!/usr/bin/python3
import sys

def factorize():
    factor_file = sys.argv[1]
    with open(factor_file) as fd:
        for line in fd:
            number = int(line)
            factors = []
            for i in range(2, number // 2 + 1):
                if number % i == 0:
                    factors.append(i)
                    number //= i
                    break
            if not factors:
                factors.append(1)
            factors.append(number)
            print("{}={}".format(line.rstrip(), "*".join(map(str, factors))))

factorize()
